import type { Quotation } from '@/types'

export async function generateQuotationPDF(quotation: Quotation): Promise<void> {
    const jsPDF = (await import('jspdf')).default
    const autoTable = (await import('jspdf-autotable')).default

    const doc = new jsPDF()
    const client = (quotation as any).clients
    const event = (quotation as any).events

    const violet = [124, 58, 237] as [number, number, number]
    const gray = [107, 114, 128] as [number, number, number]
    const dark = [17, 24, 39] as [number, number, number]

    // Header background
    doc.setFillColor(...violet)
    doc.rect(0, 0, 210, 40, 'F')

    // Logo text
    doc.setTextColor(255, 255, 255)
    doc.setFontSize(20)
    doc.setFont('helvetica', 'bold')
    doc.text('SnapFind', 15, 18)

    doc.setFontSize(10)
    doc.setFont('helvetica', 'normal')
    doc.text('AI-Powered Photo Sharing', 15, 26)

    // Quote number + status
    doc.setFontSize(12)
    doc.setFont('helvetica', 'bold')
    doc.text(quotation.quote_number, 195, 15, { align: 'right' })
    doc.setFontSize(9)
    doc.setFont('helvetica', 'normal')
    doc.text(quotation.status.toUpperCase(), 195, 23, { align: 'right' })

    // Title
    doc.setTextColor(...dark)
    doc.setFontSize(16)
    doc.setFont('helvetica', 'bold')
    doc.text(quotation.title, 15, 55)

    // Meta info columns
    doc.setFontSize(9)
    doc.setFont('helvetica', 'normal')
    doc.setTextColor(...gray)

    let y = 67
    if (client) {
        doc.setFont('helvetica', 'bold')
        doc.setTextColor(...dark)
        doc.text('Bill to', 15, y)
        doc.setFont('helvetica', 'normal')
        doc.setTextColor(...gray)
        doc.text(client.name, 15, y + 6)
        if (client.email) doc.text(client.email, 15, y + 12)
        if (client.phone) doc.text(client.phone, 15, y + 18)
    }

    doc.setFont('helvetica', 'bold')
    doc.setTextColor(...dark)
    doc.text('Details', 120, y)
    doc.setFont('helvetica', 'normal')
    doc.setTextColor(...gray)
    doc.text(`Date: ${new Date(quotation.created_at).toLocaleDateString('en-IN')}`, 120, y + 6)
    if (quotation.valid_until) {
        doc.text(`Valid until: ${quotation.valid_until}`, 120, y + 12)
    }
    if (event) {
        doc.text(`Event: ${event.title}`, 120, y + 18)
    }

    // Items table
    autoTable(doc, {
        startY: y + 32,
        head: [['#', 'Description', 'Qty', 'Rate (₹)', 'Amount (₹)']],
        body: quotation.items.map((item, i) => [
            i + 1,
            item.description,
            item.quantity,
            item.rate.toLocaleString('en-IN'),
            item.amount.toLocaleString('en-IN'),
        ]),
        headStyles: {
            fillColor: violet,
            textColor: [255, 255, 255],
            fontSize: 9,
            fontStyle: 'bold',
        },
        bodyStyles: { fontSize: 9, textColor: dark },
        columnStyles: {
            0: { cellWidth: 10, halign: 'center' },
            1: { cellWidth: 90 },
            2: { cellWidth: 20, halign: 'center' },
            3: { cellWidth: 30, halign: 'right' },
            4: { cellWidth: 35, halign: 'right' },
        },
        alternateRowStyles: { fillColor: [249, 250, 251] },
        margin: { left: 15, right: 15 },
    })

    const tableEnd = (doc as any).lastAutoTable.finalY + 10

    // Totals box
    const boxX = 120
    doc.setFillColor(249, 250, 251)
    doc.roundedRect(boxX, tableEnd, 75, 36, 3, 3, 'F')

    doc.setFontSize(9)
    doc.setTextColor(...gray)
    doc.text('Subtotal', boxX + 5, tableEnd + 10)
    doc.text(`₹${Number(quotation.subtotal).toLocaleString('en-IN')}`, 190, tableEnd + 10, { align: 'right' })

    doc.text(`GST (${quotation.tax_percent}%)`, boxX + 5, tableEnd + 19)
    doc.text(`₹${Number(quotation.tax_amount).toLocaleString('en-IN')}`, 190, tableEnd + 19, { align: 'right' })

    doc.setDrawColor(...violet)
    doc.line(boxX + 5, tableEnd + 23, 190, tableEnd + 23)

    doc.setFontSize(11)
    doc.setFont('helvetica', 'bold')
    doc.setTextColor(...violet)
    doc.text('Total', boxX + 5, tableEnd + 32)
    doc.text(`₹${Number(quotation.total).toLocaleString('en-IN')}`, 190, tableEnd + 32, { align: 'right' })

    // Notes
    if (quotation.notes) {
        const noteY = tableEnd + 50
        doc.setFontSize(9)
        doc.setFont('helvetica', 'bold')
        doc.setTextColor(...dark)
        doc.text('Notes', 15, noteY)
        doc.setFont('helvetica', 'normal')
        doc.setTextColor(...gray)
        const lines = doc.splitTextToSize(quotation.notes, 180)
        doc.text(lines, 15, noteY + 7)
    }

    // Footer
    doc.setFontSize(8)
    doc.setTextColor(...gray)
    doc.setFont('helvetica', 'normal')
    doc.text('Generated by SnapFind — AI Photo Sharing Platform', 105, 285, { align: 'center' })

    doc.save(`${quotation.quote_number}-${quotation.title.replace(/\s+/g, '-')}.pdf`)
}